src/containers/VacancyDashboard/VacancyDashboard.css
src/containers/VacancyDashboard/VacancyDashboard.js

Revert "changing tabs for dashboard"

---

src/containers/VacancyDashboard/VacancyDashboard.js

Vacancy dashboard

---

package-lock.json
src/components/NavBar/NavBar.css
src/components/NavBar/NavBar.js
src/containers/Apply/SubmitModal/SubmitModal.js
src/containers/ViewVacancyDetails/Header/Header.js
src/containers/ViewVacancyDetails/ViewVacancyDetails.js
src/hoc/Layout/Layout.js

Apply button hidden now when vacancy is closed.  NavBar updated to properly size with wider screens.

Hide apply button when vacancy closed.

---

src/containers/Apply/Forms/ApplicantDocuments/ApplicantDocuments.js

You can now upload files once and they appear, also the files display when clicking "back", also also they appear on the review screen.

Upload files once

---

src/components/UI/EditableFocusArea/EditableFocusArea.js
src/containers/Apply/Apply.js

Removed 'bachelors' from focus area options

removed bachelors from focus area

---

src/containers/ApplicantApplicationView/ApplicantApplicationView.js

Viewing the read only submission of a completed application shows demographics information now:

demographic info added to read only view of submitted application

---

src/containers/Profile/Forms/Demographics.js

Added privacy save tool tip info to profile demographics.

Added privacy save tool tip info to profile demographics.

---

src/containers/ManageDashboard/ApplicantList/IndividualScoringTable/IndividualScoringTable.js

Scoring format is now two decimals.

Scoring format is now two decimals.

---

src/containers/CreateVacancy/Forms/BasicInfo/BasicInfo.js
src/containers/CreateVacancy/Forms/FinalizeVacancy/FinalizeVacancy.js
src/containers/ViewVacancyDetails/ViewVacancyDetails.js

Changes:
Rewording of references to full contact details.
https://tracker.nci.nih.gov/browse/APPTRACK-797

Changed wording for letters of recommendation

---

src/components/Header/Login/Login.css
src/components/Header/Login/Login.js

**Changes**
We're breaking out of the unstyled, antd layout and appearance and moving to something that provides more visual cues to users about what they are clicking on.

Login menu layout / style changes

---

src/containers/ApplicantApplicationView/ApplicantApplicationView.js
src/containers/ApplicantApplicationView/Util/TransformJsonFromBackend.js

Now users can submit an application with selected focus area(s) and see them on the application submission screen.

Added focus area to submitted application summary.

---

src/containers/ApplicantApplicationView/ApplicantApplicationView.js

Changes:
- Removed extraneous e references in JS that were provoking errors.
Tested application with 2 focus areas and 0 focus areas.
No errors were detected.

Removed extraneous e references in JS that were provoking errors.

---

src/containers/Profile/Forms/EditableBasicInfo/EditableBasicInfo.js

**Change**
- Mobile (or just "phone" on the edit screen) is now a required field

Phone (mobile) required field in profile now

---

src/containers/CreateVacancy/Forms/MandatoryStatements/MandatoryStatements.js

**Changes**
- EOE statement can't be disabled any more and will always be included

EOE statement can't be disabled any more and will always be included

---

src/containers/ApplicantDashboard/ApplicantDashboard.js
src/containers/Apply/Apply.js
src/containers/Apply/SubmitModal/SubmitModal.js

**Changes**
- First letter on buttons are now capitalized

First letter on buttons are now capitalized

---

src/components/UI/InputWithCheckbox/InputWithCheckbox.js
src/containers/CreateVacancy/CreateVacancy.js
src/containers/CreateVacancy/Forms/VacancyCommittee/EditableTable/EditableTable.js
src/containers/VacancyDashboard/VacancyDashboard.js

**Changes**
- Added capitalization to Vacancy Dashboard
- Added capitalization to Create Vacancy (and related screens)

Apptrack 939 other screens

---

src/components/UI/ReviewSectionHeader/ReviewSectionHeader.js
src/containers/CreateVacancy/Forms/BasicInfo/BasicInfo.js
src/containers/CreateVacancy/Forms/BasicInfo/RequiredDocsList/RequiredDocsList.js
src/containers/CreateVacancy/Forms/VacancyCommittee/EditableTable/EditableTable.js

**Changes**
- Focus area enabled is now Focus Area Enabled
- Action table header is now Actions
- Edit section is now Edit Section
- Add more is now Add More

Three more capitalizations

---

src/containers/CreateVacancy/Forms/BasicInfo/BasicInfo.js

**Changes**
- Added two new positions for new vacancy integrations

Added two positions for vacancy integration

---

src/containers/Apply/Apply.js

This appears to fix the file duplication issue (and perhaps many other things)

This appears to fix the file duplication issue (and perhaps many other things)

---

src/constants/Roles.js
src/containers/CreateVacancy/Forms/VacancyCommittee/EditableTable/EditableCell/EditableCell.js

APPTRACT-799 Changes for extra role

---

src/containers/CreateVacancy/Forms/FinalizeVacancy/FinalizeVacancy.js
src/containers/ManageDashboard/ManageDashboard.js
src/containers/ManageDashboard/ViewVacancyDetails/ViewVacancyDetails.js

1010 - ReadOnly member vacancy details changes.

Changes for 1010 Ready only member configuration

---

src/containers/ManageDashboard/ApplicantList/ApplicantList.js

Given I am an authenticated Member( read-only) for a vacancy
When I am on the Applicants Tab for a vacancy which I am assigned that is in Voting Complete
Then I will see the following table columns with application data:
Applicant
Email

VOTING_COMPLETE state

---

src/containers/ManageDashboard/ApplicantList/ApplicantList.js

Given I am an authenticated Member( read-only) for a vacancy
When I am on the Applicants Tab for a vacancy which I am assigned that is in Individual Scoring
Then I will see the following table columns with application data:
- Applicant
- Email

APPTRACK-1012-B_(JK)

---

src/constants/checkAuth.js
src/containers/CommitteeDashboard/CommitteeDashboard.js

Given I am an authenticated Member( read-only) for a vacancy
When I click on the Your vacancies tab
Then I will be brought to a committee-dashboard page with table of 
AND There will be a table with the following columns:
Vacancy Title
Applicants (# of Applications)
Status (of Vacancy)

Dashboard columns - APPTRACK-1009-B_(JK)

---

src/constants/ApiEndpoints.js
src/containers/ViewVacancyDetails/Header/Header.js

1)Save an application as a draft
2) Save an application for a draft for the same vacancy
ACTUAL: User will have 1 draft for the same vacancy
Expected: User can not apply for a vacancy that they have a draft application for

Apptrack 1023 b (jk)

---

src/containers/ApplicantDashboard/ApplicantDashboard.js

I just updated the title the applicant sees. I changed the name from 'State' to 'Status'.

changed applicant title of State to Status

---

src/containers/ApplicantDashboard/ApplicantDashboard.js
src/containers/Apply/Apply.js
webpack/servicenow.config.js

fixed Your Application visual bug not immediately populating when Draft is created/ deleted.

Apptrack 1268 jl

---

src/containers/CreateVacancy/Forms/BasicInfo/BasicInfo.js
webpack/servicenow.config.js

Fixed Rolling Close vacancy bug with open date throwing an error for choosing a close date.

Apptrack 1279 jl

---

src/containers/ApplicantDashboard/ApplicantDashboard.js
src/hooks/useFetch.js

imported useState

---

src/components/UI/InputWithCheckbox/InputWithCheckbox.css
src/containers/CreateVacancy/Forms/BasicInfo/BasicInfo.css

fixed visual bugs in create vacancy page

fixed visual bugs on create vacancy page

---

src/containers/ApplicantDashboard/ApplicantDashboard.js

fixed sorting bug on applicant dashboard

fixed applicant dashboard sorting bug

---

src/containers/ApplicantDashboard/ApplicantDashboard.js
webpack/servicenow.config.js

ran a check for the state column to show withdrawn if an application has been withdrawn from the vacancy.

Apptrack 1302 jl

---

src/containers/Profile/Forms/Demographics.js
webpack/servicenow.config.js

updated demographics page with verbiage from Business Owners and hid buttons if no profile is present for user.

Apptrack 1161 jl

---

src/containers/ApplicantDashboard/ApplicantDashboard.js
src/containers/Apply/Forms/ApplicantDocuments/ApplicantDocuments.js

Fix for applications allowing editing once vacancy is closed
Fix for app documents buttons disabling
Fix for application allowing user to continue after deleting documents

fix for editing apps and app documents

---

src/containers/Apply/Apply.js

removed error in the catch function to allow build to complete.

removed error in Apply.js to allow build to proceed

---

src/containers/Apply/Apply.js

missed another unused error

---

src/containers/Apply/Apply.css
src/containers/Apply/Apply.js
webpack/servicenow.config.js

added the new background color for the modal

Apptrack 1284 jl

---

src/components/Util/Application/Application.test.js

[APPTRACK-1395](https://tracker.nci.nih.gov/browse/APPTRACK-1395): Write unit tests for src/components/Util/Application/Application.js

Add Unit tests for Application.js

---

src/components/Util/Vacancy/Vacancy.test.js

[APPTRACK-1392](https://tracker.nci.nih.gov/browse/APPTRACK-1392): Write unit tests for src/components/Util/Vacancy/Vacancy.js

Add Unit Tests for Vacancy component

---

__mocks__/fileMock.js
src/components/Header/Logo/Logo.test.js

[APPTRACK-1399](https://tracker.nci.nih.gov/browse/APPTRACK-1399): Write unit tests for src/components/Header/Logo/Logo.js

Add Unit Tests for Logo.js

---

src/components/Header/Login/Login.js
src/components/Header/Login/Login.test.js

[APPTRACK-1400](https://tracker.nci.nih.gov/browse/APPTRACK-1400): Write unit tests for src/components/Header/Login/Login.js

Add Unit Tests for Login.js

---

src/components/ProtectedRoute/ProtectedRoute.test.js

[APPTRACK-1390](https://tracker.nci.nih.gov/browse/APPTRACK-1390): Write unit tests for src/components/ProtectedRoute/ProtectedRoute.js

Add Unit Tests for ProtectedRoute.js

---

src/hoc/Layout/ContentTitle/ContentTitle.test.js
src/hoc/Layout/Layout.test.js
src/hoc/Layout/RouteTitles.test.js

- **Add unit tests for Layout and RouteTitles**
- **Add unit tests for ContentTitle.js**

Add Unit Tests for Layout.js, RouteTitles.js, and ContentTitle.js

---

src/containers/Profile/ApplicantProfile.test.js

Apptrack 1542 jl

---

src/containers/ViewVacancyDetails/Header/Header.js
src/containers/ViewVacancyDetails/Header/Header.test.js

Apptrack 1454

---

src/components/UI/HeaderWithLink/HeaderWithLink.test.js
src/containers/Profile/Util/ConvertDataFromBackend.test.js
src/containers/Profile/Util/ConvertDataToBackend.test.js
src/containers/ViewVacancyDetails/Divider/Divider.test.js

- **Add unit tests for ConvertDataFromBackend.js, ConvertDataToBackend.js, and Divider.js**
- **Add unit tests for HeaderWithLink.js**

Add unit tests for HeaderWithLink.js

---

src/components/ProfileModal/ProfileModal.test.js

[APPTRACK-1397](https://tracker.nci.nih.gov/browse/APPTRACK-1397): Write unit tests for src/components/ProfileModal/ProfileModal.js

Add Unit Tests for ProfileModal.js

---

src/components/UI/LabelValuePair/LabelValuePair.test.js

[APPTRACK-1370](https://tracker.nci.nih.gov/browse/APPTRACK-1370): Write unit tests for src/components/UI/LabelValuePair/LabelValuePair.js

Add Unit Tests for LabelValuePair.js

---

src/components/UI/ReviewSectionHeader/ReviewSectionHeader.test.js

[APPTRACK-1367](https://tracker.nci.nih.gov/browse/APPTRACK-1367): Write unit tests for src/components/UI/ReviewSectionHeader/ReviewSectionHeader.js

Add Unit Tests for ReviewSectionHeader.js

---

src/components/UI/Error/Error.test.js

[APPTRACK-1382](https://tracker.nci.nih.gov/browse/APPTRACK-1382): Write unit tests for src/components/UI/Error/Error.js

Add Unit Tests for Error.js

---

src/containers/Apply/Forms/ApplicantDocuments/ApplicantDocuments.js

documents getting stashed on upload button click

---

src/containers/VacancyDashboard/VacancyDashboard.js

Closes https://tracker.nci.nih.gov/browse/APPTRACK-1731
Testing: Ensure open date sorting works for live vacancies in the vacancy dashboard.

APPTRACK-1731 - live vacancies Open Date sorting not working

---

webpack/servicenow.postbuild.js

Closes https://tracker.nci.nih.gov/browse/APPTRACK-1614
Testing: run npm run build, Ensure the html tags are added to the index.html file in the right position, test the styling of the webpages look right.

APPTRACK-1614 - 508 Compliance: Add Language Attribute to HTML

---

src/components/UI/UserPicker/UserPicker.test.js

[APPTRACK-1369](https://tracker.nci.nih.gov/browse/APPTRACK-1369): Write unit tests for src/components/UI/UserPicker/UserPicker.js

Add Unit Tests for UserPicker.js

---

src/App.less
src/components/Footer/LegalStatement/LegalStatement.css
src/components/Footer/LegalStatement/LegalStatement.js
src/containers/Home/Home.css
src/containers/Home/Home.js

Closes
[APPTRACK-1649](https://tracker.nci.nih.gov/browse/APPTRACK-1649)
[APPTRACK-1611](https://tracker.nci.nih.gov/browse/APPTRACK-1611)
Jest tests running with no error

APPTRACK-1611, APPTRACK-1649 fix link issues

---

.github/workflows/main.yml
src/containers/Application/Application.js
src/containers/Application/TriageWidget/TriageWidget.css
src/containers/Application/TriageWidget/TriageWidget.js
src/containers/CreateVacancy/Forms/BasicInfo/BasicInfo.js
src/containers/Home/Home.js

Closes [APPTRACK-1772](https://tracker.nci.nih.gov/browse/APPTRACK-1772), [APPTRACK-1773](https://tracker.nci.nih.gov/browse/APPTRACK-1773), [APPTRACK-1775](https://tracker.nci.nih.gov/browse/APPTRACK-1775)
Testing:
Please ensure texts are showing up as per the screenshots. I have not been able to test text removal as there are open vacancies in dev environment.
Screenshots

APPTRACK-1772,1773,1775 Text changes

---

src/containers/Application/TriageWidget/TriageWidget.js

Remove some ununsed imports for APPTRACK-1773 so to be able to build the project.

Remove some ununsed imports for APPTRACK-1773

---

src/components/UI/InfoCard/InfoCardRow/InfoCardRow.js
src/components/UI/InfoCard/InfoCardRow/InfoCardRow.test.js

[APPTRACK-1375](https://tracker.nci.nih.gov/browse/APPTRACK-1375): Write unit tests for src/components/UI/InfoCard/InfoCardRow/InfoCardRow.js

Added Tests for InfoCardRow.js

---

src/components/UI/InfoCard/InfoCard.test.js

[APPTRACK-1374](https://tracker.nci.nih.gov/browse/APPTRACK-1374): Write unit tests for src/components/UI/InfoCard/InfoCard.js

Added Tests for InfoCard.js

---

src/components/UI/SwitchFormItemEditor/SwitchFormItemEditor.js
src/components/UI/SwitchFormItemEditor/SwitchFormItemEditor.test.js

[APPTRACK-1368](https://tracker.nci.nih.gov/browse/APPTRACK-1368): Write unit tests for src/components/UI/SwitchFormItemEditor/SwitchFormItemEditor.js

Added Tests for SwitchFormItemEditor.js

---

src/components/UI/SwitchFormItem/SwitchFormItem.test.js

[APPTRACK-1376](https://tracker.nci.nih.gov/browse/APPTRACK-1376): Write unit tests for src/components/UI/SwitchFormItem/SwitchFormItem.js

Added Tests for SwitchFormItem.js

---

src/components/UI/Error/__snapshots__/Error.test.js.snap
src/constants/ApiEndpoints.js
src/containers/Apply/Apply.js
src/containers/Apply/Apply.test.js
src/containers/Apply/ApplyMockData.js
src/containers/Apply/Forms/ApplicantDocuments/ApplicantDocuments.js
src/containers/Apply/SubmitModal/SubmitModal.js
src/containers/Apply/SubmitModal/SubmitModal.test.js
src/containers/Apply/SubmitModal/SubmitModalMockData.js
webpack/servicenow.config.js

Applicant document rework and Jest test coverages over changes made.

apptrack-1549-featureBranch-jl

---

src/components/UI/EditableField/EditableField.test.js

[APPTRACK-1377](https://tracker.nci.nih.gov/browse/APPTRACK-1377): Write unit tests for src/components/UI/EditableField/EditableField.js

Added Tests for EditableField.js

---

src/components/UI/InputWithCheckbox/InputWithCheckbox.test.js

[APPTRACK-1378](https://tracker.nci.nih.gov/browse/APPTRACK-1378): Write unit tests for src/components/UI/InputWithCheckbox/InputWithCheckbox.js

Added Unit Test for InputWithCheckbox.js

---

src/containers/Apply/Apply.js
webpack/servicenow.config.js

Fixes bug : [APPTRACK-1812](https://tracker.nci.nih.gov/browse/APPTRACK-1812)
When errored page should redirect to documents step in application process.

APPTRACK-1812 - Redirect user to documents page if error encountered

---

src/components/UI/InputWithButton/InputWithButton.test.js

[APPTRACK-1379](https://tracker.nci.nih.gov/browse/APPTRACK-1379): Write unit tests for src/components/UI/InputWithButton/InputWithButton.js

Added Unit Test for InputWithButton.js

---

package-lock.json
package.json
src/hooks/useFetch.test.js

[APPTRACK-1401](https://tracker.nci.nih.gov/browse/APPTRACK-1401): Write unit tests for src/hooks/useFetch.js

Added Tests for useFetch.js

---

package-lock.json
package.json
src/hooks/useAuth.test.js

[APPTRACK-1402](https://tracker.nci.nih.gov/browse/APPTRACK-1402): Write unit tests for src/hooks/useAuth.js

Added Tests for useAuth.js

---

package-lock.json
package.json
src/hooks/useTimeout.test.js

[APPTRACK-1403](https://tracker.nci.nih.gov/browse/APPTRACK-1403): Write unit tests for src/hooks/useTimeout.js

Added Tests for useTimeout.js

---

src/context/TimeoutContext.test.js

[APPTRACK-1355](https://tracker.nci.nih.gov/browse/APPTRACK-1355): Write unit tests for src/context/TimeoutContext.js

Added Tests for TimeoutContext.js

---

src/containers/Apply/Forms/DemographicsStep/DemographicsStepForm/DemographicsStepForm.test.js

[APPTRACK-1405](https://tracker.nci.nih.gov/browse/APPTRACK-1405): Write unit tests for src/containers/Apply/Forms/DemographicsStep/DemographicsStepForm/DemographicsStepForm.js

Added Tests for DemographicsStepForm.js

---

src/containers/Apply/Forms/References/ApplicantReferences.js
src/containers/Apply/Forms/References/ApplicantReferences.test.js
src/index.html

[APPTRACK-1406](https://tracker.nci.nih.gov/browse/APPTRACK-1406): Write unit tests for src/containers/Apply/Forms/References/ApplicantReferences.js

Added Tests for ApplicantReferences.js

---

src/containers/Apply/Forms/Review/Review.js
src/containers/Apply/Forms/Review/Review.test.js

[APPTRACK-1408](https://tracker.nci.nih.gov/browse/APPTRACK-1408): Write unit tests for src/containers/Apply/Forms/Review/Review.js

Added Tests for Review.js

---

src/containers/CreateVacancy/Forms/BasicInfo/BasicInfo.js
src/containers/ManageDashboard/ApplicantList/ApplicantList.js

Fixing an issue that came up while building the app.

SSJ-80 fix build issue for blank href

---

src/components/UI/FileUploadAndDisplay/FileUploadAndDisplay.js
src/components/UI/FileUploadAndDisplay/FileUploadAndDisplay.test.js

[SSJ-149](https://tracker.nci.nih.gov/browse/SSJ-149): Write unit tests for src/components/UI/FileUploadAndDisplay/FileUploadAndDisplay.js

Ssj 149 mw

---

src/components/NavBar/NavBar.js
src/components/NavBar/NavBar.test.js
src/containers/ChairDashboard/ChairDashboard.js
src/containers/CommitteeDashboard/CommitteeDashboard.js
src/hoc/Layout/Layout.test.js
webpack/servicenow.config.js

Bug description - For a user with no tenants, my Vacancies is showing up

Fix Empty My vacancies for users with no tenants

---

package-lock.json
package.json
src/App.js
src/components/Header/Login/Login.js
src/components/Header/Login/Login.test.js

- Remember last tenant selected by the user
- If the user has access to one tenant, by default select that tenant.

SSJ-30 remember last tenant

---

src/components/Util/RoleValidator/RoleValidator.js
src/containers/ManageDashboard/ManageDashboard.js

SSJ-371 manage dashboard bug

---

package-lock.json
package.json
src/App.js
src/components/Header/Login/Login.js
src/components/Header/Login/Login.test.js

SSJ-373 revert cookies

---

src/components/NavBar/NavBar.css
src/components/NavBar/NavBar.js
src/components/Util/RoleValidator/RoleValidator.js

…ror regarding Your Vacancy tab, hovering on sub item in your vacancy keeps text white

ssj-378 HR Specialist displays Your Vacancies tab

---

src/containers/Apply/Apply.js
src/containers/Apply/SubmitModal/SubmitAppWorkflow/SubmitEdittedApp.js
src/containers/Apply/SubmitModal/SubmitAppWorkflow/SubmitNewApp.js
webpack/servicenow.config.js

…n case app draft save api fails when Apply is clicked

SSJ-74v2-JL

---

src/containers/Apply/SubmitModal/SubmitAppWorkflow/SubmitNewApp.js

adds draft id to json obj for application submission api

ssj-346-jl

---

src/containers/ManageDashboard/ApplicantList/ApplicantList.css
src/containers/ManageDashboard/ApplicantList/ApplicantList.js
src/containers/ManageDashboard/ApplicantList/IndividualScoringTable/IndividualScoringTable.js
src/containers/ManageDashboard/ApplicantList/IndividualScoringTable/IndividualScoringTable.test.js

Add a new column and filter in scoring phase fixed close and rolling close vacancies.
Update set : https://ezapps-dev.nih.gov/nav_to.do?uri=sys_update_set.do?sys_id=6f19d7a287422a10b7af2176cebb3576

SSJ-369 Create Focus Area Filter

---

jest.config.js
package-lock.json
package.json

- npm install
- test that all axios calls are working w/o any failures.

SSJ-335 update axios

---

src/containers/CommitteeDashboard/ApplicantList/ApplicantList.js
src/containers/ManageDashboard/ApplicantList/ApplicantList.js

Fixes the bug of not disoplaying focus area for committee member, chair

SSJ-425 Stadtman Committee member not displaying focus area

---

src/containers/ApplicantApplicationView/ApplicantApplicationView.js
src/containers/ApplicantApplicationView/Util/TransformJsonFromBackend.js
src/containers/Application/Application.js
src/containers/ManageDashboard/ApplicantList/IndividualScoringTable/IndividualScoringTable.js

fixes display issue of Focus Area not displaying if only 1 is selected

SSJ-452 Stadtman applicant selecting one focus area causes null value to display for VM

---

src/components/UI/UserPicker/UserPicker.js
src/components/UI/UserPicker/UserPicker.test.js
src/containers/CommitteeDashboard/ApplicantList/ApplicantList.js
src/containers/CreateVacancy/CreateVacancy.js
src/containers/CreateVacancy/CreateVacancy.test.js
src/containers/VacancyDashboard/VacancyDashboard.js
src/context/AuthContext.js

SSJ-375 refactor user list

---

src/containers/Application/Application.js
src/containers/Application/Application.test.js

closes SSJ-499. Ensures vacancy manager has access to widget with proper roles

SSJ-499 Chair Triage decision undefined

---

src/hoc/Layout/Layout.css
src/hoc/Layout/Layout.js

SSJ-527 - Add NIH Government Funding Lapse Banner to SSJ
